# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7f78b0fc57e791daba229925dbda76559c4c92b822277f7ac88b22e27e496058e35a4d24d148d1044bef22c0641b50931c0797e7230e6de3e4ffd25f807d8ef

test:
  secret_key_base: 9272978007bd47ff811bd12675e1f71f3f244b62aa0d5a3f49426a2a6f8c4eb7fa604e1e6d17051b939a7982170f6bed80c4d13ecc47be3610d8d6ec6e5f47e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
